kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fabric-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: fabricfiles1
 
