kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv3
  labels:
    type: local
    name: fabricfiles3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /MSP_Org3/config
  
