kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv2
  labels:
    type: local
    name: fabricfiles2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /MSP_Org2/config
  
