kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv1
  labels:
    type: local
    name: fabricfiles1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /MSP_Org1/config
  
