apiVersion: v1
kind: Service
metadata:
  name: peer0org1
  labels:
    run: peer0org1
spec:
  type: ClusterIP
  selector:
    name: peer0org1
  ports:
  - protocol: TCP
    port: 7051
    name: grpc
    targetPort: 7051
  - protocol: TCP
    port: 7061
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
