apiVersion: v1
kind: Pod
metadata:
    name: channel-binaries-org2
spec:
    nodeName: worker-node-2
    containers:
    - name: alpine
      image: alpine:latest
      command: ['sleep', 'infinity']
      volumeMounts:
      - name: fabric-pv2
        mountPath: /MSP_Org2/config
    volumes:
    - name: fabric-pv2
      persistentVolumeClaim:
        claimName: fabric-pvc2

