apiVersion: v1
kind: Pod
metadata:
    name: channel-binaries-org3
spec:
    nodeName: worker-node-2
    containers:
    - name: alpine
      image: alpine:latest
      command: ['sleep', 'infinity']
      volumeMounts:
      - name: fabric-pv3
        mountPath: /MSP_Org3/config
    volumes:
    - name: fabric-pv3
      persistentVolumeClaim:
        claimName: fabric-pvc3

