apiVersion: v1
kind: Service
metadata:
  name: orderer2
  labels: 
    run: orderer2
spec:
  type: ClusterIP
  selector:
    name: orderer2
  ports:
  - protocol: TCP
    port: 8050
    name: grpc
    targetPort: 8050

    
    
