apiVersion: apps/v1
kind: Deployment
metadata: 
  name: orderer4
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: orderer4
  template:
    metadata:
      labels:
        name: orderer4        
    spec:
      #nodeName: worker-node-1
      volumes:
          
        - name: fabric-pv
          persistentVolumeClaim:
            claimName: fabric-pvc

      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.0.1
          command: [ "sh", "-c", "orderer" ]
          env:
          - name: TZ
            value: "Asia/Kolkata"
          - name: ORDERER_CFG_PATH
            value: /repo/config/
          - name: CONFIGTX_ORDERER_ADDRESSES
            value: "orderer4.ai.com:10050"
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: 0.0.0.0
          - name: ORDERER_GENERAL_LISTENPORT
            value: "10050"
          - name: ORDERER_GENERAL_LOGLEVEL
            value: debug
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/msp/
          - name: ORDERER_GENERAL_LOCALMSPID
            value: OrdererMSP
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: file
          - name: ORDERER_GENERAL_GENESISFILE
            value: /repo/config/genesis.block
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/tls/server.key
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/tls/server.crt
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/tls/ca.crt
          - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/tls/server.key
          - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            value: /repo/config/crypto-config/ordererOrganizations/ai.com/orderers/orderer4.ai.com/tls/server.crt
          volumeMounts:
          - mountPath: /repo/config/
            name: fabric-pv